import { defineConfig, type Plugin } from 'vite';

/** FNV-1a, so the cache version needs no node imports (the repo carries no @types/node). */
function fnv(text: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(16).padStart(8, '0');
}

/**
 * The precache service worker (ROADMAP task 172), written by the build
 * itself rather than by a plugin dependency.
 *
 * The whole game is one hashed JS file plus an HTML shell, a manifest and
 * three icons — a workbox pipeline for that is a lorry for a letter. This
 * plugin waits for the bundle, lists what actually shipped, and writes a
 * ~40-line service worker with that list baked in. The cache name carries
 * a hash of the list, so a new deploy installs a new cache and the old one
 * is deleted on activate; a build that changes nothing produces the same
 * worker byte-for-byte and browsers skip the update entirely.
 *
 * Offline behaviour: precached files are served cache-first (they are
 * content-hashed or tiny), navigations fall back to the cached shell, and
 * anything else goes to the network. That is the whole of it — the child
 * in the back of the car gets the road; nothing clever gets to break.
 */
function precacheWorker(): Plugin {
  let base = '/';
  return {
    name: 'wandering-bard-precache-worker',
    apply: 'build',
    configResolved(config) {
      base = config.base;
    },
    generateBundle(_options, bundle) {
      const hashed = Object.keys(bundle).filter((f) => !f.endsWith('.map'));
      // The public/ files Vite copies verbatim (the PWA shell from task 171).
      const shell = [
        '',
        'index.html',
        'manifest.webmanifest',
        'icons/icon-192.png',
        'icons/icon-512.png',
        'icons/apple-touch-icon.png',
      ];
      const urls = [...new Set([...shell, ...hashed])].map((f) => base + f);
      const version = fnv(urls.join('\n'));

      const worker = `// Generated by vite.config.ts (task 172). Cache ${version}.
const CACHE = 'wandering-bard-${version}';
const URLS = ${JSON.stringify(urls)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(URLS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (url.origin !== location.origin) return;
  event.respondWith(
    caches.match(event.request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      if (event.request.mode === 'navigate') {
        return caches.match('${base}index.html').then((shell) => shell ?? fetch(event.request));
      }
      return fetch(event.request);
    })
  );
});
`;
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: worker });
    },
  };
}

export default defineConfig({
  base: '/WanderingBardGame/',
  plugins: [precacheWorker()],
});
